export const bluepagesApiData = {
    entryType: 'workday',
    c: 'us',
    dn: 'uid=01A02B03C,c=us,ou=bluepages,o=ibm.com',
    callupName: 'Test, Name',
    co: 'United States',
    costCenter: 'DDS',
    createdDate: '2020-01-03',
    div: '1G',
    divestitureFlag: false,
    employeeCountryCode: '897',
    functionalManagerUid: '123456789',
    hrActive: 'A',
    hrOrganizationCode: '0A',
    languages: ['English'],
    mail: ['name.test@ibm.com', '01A02B03C@ibm.com'],
    manager: 'uid=839814897,c=us,ou=bluepages,o=ibm.com',
    inCountryManagerUid: '123456789',
    managerPSC: '897',
    notesEmail: 'Name Test/US/IBM',
    notesShortName: '01A02B03C',
    notesMailDomain: 'IBM',
    preferredContactMethod: 'EM',
    preferredIdentity: 'name.test@ibm.com',
    profileLastUpdated: '2020-01-27T13:52:59.376Z',
    psc: '897',
    role: 'Role',
    serial: '01A02B03C',
    uid: '01A02B03C',
    timeZone: '-05:00',
    timeZoneCode: 'America/New_York',
    nameFull: 'Name Test',
    cn: ['Name Test', 'Test, Name'],
    iot: 'North America IOT',
    imt: 'US IMT',
    workdayWorkerID: '123456',
    workerId: '123456',
    address: {
        business: {
            country: 'US',
            locality: 'RESEARCH TRIANGLE PARK',
            state: 'NC',
            zip: '27709-2195',
            location: 'Research Triangle Park, NC, United States',
            stateCo: 'NC, Research Triangle Park, United States',
            address: ['3039 E CORNWALLIS RD', 'P.O. BOX 12195'],
        },
    },
    oooSettings: {
        message: false,
        date: true,
    },
    workLocation: {
        building: '062',
        code: 'RPL',
        campusID: 'RTPMAIN',
    },
    telephone: {
        mobile: '1-1234567890',
        office: '1-1234567890',
    },
    org: {
        group: 'F&O',
        title: 'Finance and Operations',
        unit: 'CIO',
        code: '0A',
    },
    legalEntity: {
        groupCode: 'IBMH',
        groupId: 'Dark Blue',
        name: 'IBM USA',
        code: '0147',
    },
    employeeType: {
        isEmployee: true,
        isManager: false,
        title: 'IBM employee, Regular',
        code: 'P',
    },
    dept: {
        title: 'Department',
        code: 'DDS',
    },
    name: {
        last: 'Test',
        first: 'Name',
    },
    workplaceIndicator: 'S',
    startDate: '2020-01-15',
    notesMailFile: 'data0/126/123456.nsf',
    notesMailServer: 'CN=ABCDE123/OU=40/OU=LLN/O=IBM',
    slackId: 'QWERTY',
    slackUsername: 'name.test',
    preferredSlackId: 'QWERTY',
    preferredSlackUsername: 'name.test',
};
